export type Product = {
  id: number;
  name: string;
  brand: string;
  flavor: string;
  flavorCategory: string;
  price: number;
  stock: number;
  puffs: number;
  nicotine: string;
  gradient: string;
  emoji: string;
  description: string;
  featured?: boolean;
};

export const WHATSAPP_NUMBER = "5214422038170"; // ← Cambia por tu número

export const products: Product[] = [
  {
    id: 1,
    name: "SMOK Nord 5",
    brand: "SMOK",
    flavor: "Mango Ice",
    flavorCategory: "Frutal",
    price: 89.99,
    stock: 5,
    puffs: 2000,
    nicotine: "5%",
    gradient: "from-orange-500 via-yellow-400 to-amber-300",
    emoji: "🥭",
    description: "Sabor tropical con toque refrescante de hielo",
    featured: true,
  },
  {
    id: 2,
    name: "Lost Mary OS5000",
    brand: "Lost Mary",
    flavor: "Blueberry Sour Razz",
    flavorCategory: "Frutal",
    price: 75.0,
    stock: 12,
    puffs: 5000,
    nicotine: "5%",
    gradient: "from-blue-600 via-indigo-500 to-purple-500",
    emoji: "🫐",
    description: "Arándano ácido con frambuesa, intensamente jugoso",
    featured: true,
  },
  {
    id: 3,
    name: "Elf Bar BC5000",
    brand: "Elf Bar",
    flavor: "Watermelon Ice",
    flavorCategory: "Frutal",
    price: 65.0,
    stock: 3,
    puffs: 5000,
    nicotine: "5%",
    gradient: "from-green-400 via-emerald-400 to-teal-400",
    emoji: "🍉",
    description: "Sandía fresca con hielo menthol suave",
    featured: false,
  },
  {
    id: 4,
    name: "Geek Bar Pulse",
    brand: "Geek Bar",
    flavor: "Strawberry Banana",
    flavorCategory: "Frutal",
    price: 70.0,
    stock: 8,
    puffs: 15000,
    nicotine: "5%",
    gradient: "from-pink-500 via-rose-400 to-yellow-300",
    emoji: "🍓",
    description: "Fresa dulce con plátano cremoso, combinación perfecta",
    featured: true,
  },
  {
    id: 5,
    name: "Vozol Star 12000",
    brand: "Vozol",
    flavor: "Cool Mint",
    flavorCategory: "Mentol",
    price: 95.0,
    stock: 0,
    puffs: 12000,
    nicotine: "5%",
    gradient: "from-cyan-400 via-sky-400 to-blue-400",
    emoji: "🧊",
    description: "Menta pura extra fría, sensación ártica",
    featured: false,
  },
  {
    id: 6,
    name: "Funky Republic Ti7000",
    brand: "Funky Republic",
    flavor: "Pink Lemonade",
    flavorCategory: "Cítrico",
    price: 80.0,
    stock: 2,
    puffs: 7000,
    nicotine: "5%",
    gradient: "from-pink-400 via-fuchsia-400 to-purple-400",
    emoji: "🍋",
    description: "Limonada rosa refrescante con toque dulce",
    featured: false,
  },
  {
    id: 7,
    name: "Hyde Mag 4500",
    brand: "Hyde",
    flavor: "Peach Ice",
    flavorCategory: "Frutal",
    price: 55.0,
    stock: 15,
    puffs: 4500,
    nicotine: "5%",
    gradient: "from-amber-400 via-orange-300 to-red-300",
    emoji: "🍑",
    description: "Durazno maduro con hielo, suave y refrescante",
    featured: false,
  },
  {
    id: 8,
    name: "Raz TN9000",
    brand: "RAZ",
    flavor: "Grape Ice",
    flavorCategory: "Frutal",
    price: 85.0,
    stock: 6,
    puffs: 9000,
    nicotine: "5%",
    gradient: "from-purple-600 via-violet-500 to-purple-400",
    emoji: "🍇",
    description: "Uva oscura con iceberg menthol explosivo",
    featured: false,
  },
  {
    id: 9,
    name: "Elf Bar TE6000",
    brand: "Elf Bar",
    flavor: "Tobacco Classic",
    flavorCategory: "Tabaco",
    price: 60.0,
    stock: 4,
    puffs: 6000,
    nicotine: "5%",
    gradient: "from-yellow-800 via-amber-700 to-yellow-600",
    emoji: "🌿",
    description: "Sabor tabaco clásico suave, para los puristas",
    featured: false,
  },
  {
    id: 10,
    name: "Lost Mary BM5000",
    brand: "Lost Mary",
    flavor: "Triple Mango",
    flavorCategory: "Frutal",
    price: 78.0,
    stock: 9,
    puffs: 5000,
    nicotine: "5%",
    gradient: "from-yellow-400 via-orange-400 to-amber-500",
    emoji: "🥭",
    description: "Triple dosis de mango, dulce e intenso",
    featured: true,
  },
  {
    id: 11,
    name: "Geek Bar Skyview",
    brand: "Geek Bar",
    flavor: "Mint Tobacco",
    flavorCategory: "Tabaco",
    price: 72.0,
    stock: 7,
    puffs: 25000,
    nicotine: "5%",
    gradient: "from-slate-600 via-gray-500 to-slate-400",
    emoji: "🚬",
    description: "Tabaco con menta fresca, clásico moderno",
    featured: false,
  },
  {
    id: 12,
    name: "Pastel Cartel X35K",
    brand: "Pastel Cartel",
    flavor: "Blue Razz Lemonade",
    flavorCategory: "Cítrico",
    price: 110.0,
    stock: 1,
    puffs: 35000,
    nicotine: "5%",
    gradient: "from-blue-400 via-violet-400 to-cyan-300",
    emoji: "⚡",
    description: "Frambuesa azul con limonada, el más largo del mercado",
    featured: true,
  },
];

export const brands = ["Todas", ...Array.from(new Set(products.map((p) => p.brand)))];
export const flavorCategories = ["Todas", ...Array.from(new Set(products.map((p) => p.flavorCategory)))];

export const simulatedSales = [
  { id: 1, product: "Lost Mary OS5000 – Blueberry", qty: 3, total: 225.0, date: "2026-05-04", customer: "Carlos M." },
  { id: 2, product: "Elf Bar BC5000 – Watermelon", qty: 2, total: 130.0, date: "2026-05-04", customer: "Valeria G." },
  { id: 3, product: "Geek Bar Pulse – Strawberry", qty: 1, total: 70.0, date: "2026-05-03", customer: "Diego R." },
  { id: 4, product: "SMOK Nord 5 – Mango Ice", qty: 4, total: 359.96, date: "2026-05-03", customer: "Lucía P." },
  { id: 5, product: "Hyde Mag 4500 – Peach Ice", qty: 2, total: 110.0, date: "2026-05-02", customer: "Tomás F." },
  { id: 6, product: "Lost Mary BM5000 – Triple Mango", qty: 3, total: 234.0, date: "2026-05-02", customer: "Agustina S." },
  { id: 7, product: "RAZ TN9000 – Grape Ice", qty: 1, total: 85.0, date: "2026-05-01", customer: "Mateo L." },
  { id: 8, product: "Pastel Cartel X35K", qty: 2, total: 220.0, date: "2026-05-01", customer: "Sofía T." },
];
